# Simulation Configuration
simulation:
  duration: 10  # years
  time_step: 1  # year
  random_seed: 42

# Economic Parameters
economic:
  initial_exchange_rate: 85.0
  initial_port_efficiency: 0.7
  baseline_gdp: 1000000000  # USD
  garment_gdp_share: 0.2
  agriculture_gdp_share: 0.15
  remittances_gdp_share: 0.1
  tech_gdp_share: 0.05
  informal_gdp_share: 0.5
  garment_growth_rate: 0.05
  agriculture_growth_rate: 0.03
  remittances_growth_rate: 0.04
  tech_growth_rate: 0.15
  informal_growth_rate: 0.02
  garment_employment: 4000000
  agriculture_employment: 20000000
  tech_employment: 500000
  informal_employment: 30000000
  garment_productivity: 1.0
  agriculture_productivity: 1.0
  tech_productivity: 1.5
  informal_productivity: 0.8
  rural_interest_rate: 0.12
  urban_interest_rate: 0.08
  rural_access_rate: 0.4
  urban_access_rate: 0.7
  rural_default_rate: 0.08
  urban_default_rate: 0.05
  exchange_rate_volatility: 0.02

# Environmental Parameters
environmental:
  initial_temperature: 25.0
  initial_precipitation: 0.0
  initial_sea_level: 0.0
  initial_cyclone_probability: 0.1
  temperature_increase_rate: 0.02
  sea_level_rise_rate: 0.003
  monsoon_intensity_factor: 1.0
  cyclone_probability_increase: 0.01
  ganges_initial_water_level: 5.0
  brahmaputra_initial_water_level: 6.0
  meghna_initial_water_level: 4.0
  ganges_initial_flow_rate: 1000.0
  brahmaputra_initial_flow_rate: 1200.0
  meghna_initial_flow_rate: 800.0
  ganges_initial_sediment_load: 0.5
  brahmaputra_initial_sediment_load: 0.6
  meghna_initial_sediment_load: 0.4
  ganges_catchment_area: 1.0
  brahmaputra_catchment_area: 1.2
  meghna_catchment_area: 0.8
  initial_soil_quality: 1.0
  initial_irrigation_coverage: 0.3
  initial_groundwater_level: 10.0
  initial_arsenic_level: 0.1
  initial_water_quality: 1.0
  flood_threshold: 10.0
  baseline_yield: 1000.0
  sustainable_groundwater_level: 10.0
  groundwater_extraction_rate: 0.01
  arsenic_increase_rate: 0.001

# Demographic Parameters
demographic:
  initial_population: 170000000
  initial_population_0_14: 0.3
  initial_population_15_64: 0.65
  initial_population_65_plus: 0.05
  initial_gender_ratio: 0.95
  initial_urban_share: 0.4
  initial_rural_urban_migration: 0.02
  initial_international_migration: 0.01
  initial_remittance_flow: 0.0
  initial_literacy_rate: 0.75
  initial_primary_education: 0.4
  initial_secondary_education: 0.3
  initial_tertiary_education: 0.1
  initial_education_gender_gap: 0.1
  initial_labor_force_participation: 0.6
  initial_female_participation: 0.4
  initial_agriculture_employment: 0.4
  initial_industry_employment: 0.2
  initial_services_employment: 0.4
  initial_gini_coefficient: 0.32
  initial_poverty_rate: 0.2
  initial_bottom_20_share: 0.05
  initial_top_20_share: 0.45
  birth_rate: 0.02
  death_rate: 0.005
  literacy_improvement_rate: 0.01
  primary_education_improvement_rate: 0.01
  secondary_education_improvement_rate: 0.01
  tertiary_education_improvement_rate: 0.01
  gender_gap_reduction_rate: 0.02
  labor_force_growth_rate: 0.01
  female_participation_growth_rate: 0.02
  poverty_reduction_rate: 0.02
  remittance_rate: 0.7

# Infrastructure Parameters
infrastructure:
  initial_road_length: 350000
  initial_paved_ratio: 0.6
  initial_congestion: 0.5
  initial_waterway_length: 6000
  initial_navigable_ratio: 0.7
  initial_waterway_efficiency: 0.6
  initial_rail_length: 3000
  initial_rail_operational: 0.8
  initial_rail_capacity: 0.7
  initial_power_capacity: 25000
  initial_renewable_share: 0.1
  initial_load_shedding: 0.1
  initial_grid_efficiency: 0.85
  initial_transmission_loss: 0.15
  initial_electricity_access: 0.95
  initial_mobile_penetration: 0.8
  initial_mobile_coverage: 0.9
  initial_data_usage: 0.5
  initial_internet_penetration: 0.4
  initial_broadband_access: 0.3
  initial_internet_speed: 5.0
  initial_urban_housing: 10000000
  initial_urban_housing_quality: 0.6
  initial_slum_ratio: 0.3
  initial_rural_housing: 15000000
  initial_rural_housing_quality: 0.5
  initial_housing_vulnerability: 0.4
  initial_garment_resilience: 0.7
  initial_garment_logistics: 0.6
  initial_port_efficiency: 0.7
  initial_agri_resilience: 0.6
  initial_storage_capacity: 0.5
  initial_agri_distribution: 0.5
  road_improvement_rate: 0.01
  waterway_improvement_rate: 0.01
  waterway_efficiency_improvement: 0.01
  rail_improvement_rate: 0.01
  power_capacity_growth: 0.05
  renewable_growth_rate: 0.1
  grid_improvement_rate: 0.01
  loss_reduction_rate: 0.01
  mobile_growth_rate: 0.05
  data_usage_growth: 0.2
  internet_growth_rate: 0.1
  speed_improvement_rate: 0.15
  urban_housing_improvement: 0.02
  slum_reduction_rate: 0.01
  rural_housing_improvement: 0.01
  vulnerability_reduction_rate: 0.01
  garment_resilience_improvement: 0.01
  logistics_improvement_rate: 0.01
  agri_resilience_improvement: 0.01
  storage_improvement_rate: 0.01

# Governance Parameters
governance:
  initial_bureaucracy_efficiency: 0.5
  initial_corruption_index: 0.3
  initial_transparency: 0.4
  initial_judicial_independence: 0.5
  initial_judicial_efficiency: 0.4
  initial_judicial_access: 0.3
  initial_local_effectiveness: 0.4
  initial_local_participation: 0.3
  initial_local_accountability: 0.4
  initial_economic_policy: 0.5
  initial_policy_implementation: 0.4
  initial_policy_adaptability: 0.5
  initial_social_policy: 0.4
  initial_social_implementation: 0.3
  initial_policy_coverage: 0.5
  initial_environmental_policy: 0.3
  initial_environmental_implementation: 0.2
  initial_policy_enforcement: 0.3
  initial_gender_representation: 0.2
  initial_wage_gap: 0.3
  initial_gender_access: 0.6
  initial_institutional_trust: 0.4
  initial_social_capital: 0.5
  initial_inequality_perception: 0.7
  initial_voter_turnout: 0.5
  initial_civil_society: 0.4
  initial_media_freedom: 0.5
  initial_ngo_effectiveness: 0.6
  initial_ngo_coverage: 0.4
  initial_ngo_sustainability: 0.5
  initial_advocacy_effectiveness: 0.5
  initial_ngo_influence: 0.4
  initial_ngo_coordination: 0.5
  initial_stability_index: 0.6
  initial_policy_continuity: 0.5
  initial_institutional_trust: 0.4
  bureaucracy_improvement_rate: 0.01
  corruption_reduction_rate: 0.01
  judicial_independence_improvement: 0.01
  judicial_efficiency_improvement: 0.01
  local_effectiveness_improvement: 0.01
  economic_policy_improvement: 0.01
  implementation_improvement: 0.01
  social_policy_improvement: 0.01
  coverage_improvement: 0.01
  environmental_policy_improvement: 0.01
  enforcement_improvement: 0.01
  gender_representation_improvement: 0.01
  wage_gap_reduction: 0.01
  trust_improvement: 0.01
  social_capital_improvement: 0.01
  voter_turnout_improvement: 0.01
  media_freedom_improvement: 0.01
  development_effectiveness_improvement: 0.01
  advocacy_effectiveness_improvement: 0.01
  influence_improvement: 0.01
  stability_improvement: 0.01
  continuity_improvement: 0.01 